### ISSUE TITLE
Selectable APY time interval on homepage

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1026]
We've updated the OUSD homepage to more clearly state that the APY shown is actual and historical rather than current or forward-looking. Let's take this one step further by allowing the viewer to choose a different historical measure of the protocol's performance. My suggestion is to make "year" obviously clickable and make the other options "week" and "month". We could underline it with a little gear icon to the right or just use an ugly, native `select` element instead of reinventing it. Either way, let's default to the 30-day/monthly choice. A week is often not long enough to include a representative sample of yield-generating events, but a year is arguably a worse indicator of possible future performance.

Also, it's a little awkward to say "month" when the calculation is actually the trailing 30-day period. I think we should be consistent about using numbers or words, so here are the two options in my mind:

**Option A** (good)
- "year"
- "month"*
- "week"

**Option B** (good)
- "365 days"
- "30 days"*
- "7 days"

~~**Other**~~ (bad)
- "year"
- "30 days"*
- "week"

\* default selection

<img width="488" alt="Screen Shot 2022-06-20 at 9 54 00 AM" src="https://user-images.githubusercontent.com/273937/174653906-51243f13-37fd-4438-9e6a-56bb5bf0a023.png">

**Comment by staa99** [comment]
Hi @micahalcorn,

I think using `Option B` is great. That way, the calculation feels more accurate and conveys the right information to the user as well. For styling, I think underlining the `year` and making it clickable to show a little component that displays the options is a good idea. Defaulting to the `month` is probably best since it provides a closer estimate of the current situation. I can pick this up if you don't mind. It'd be my first contribution to the dApp so I might need some help figuring some stuff out.

**Comment by micahalcorn** [comment]
> Hi @micahalcorn,
> 
> I think using `Option B` is great. That way, the calculation feels more accurate and conveys the right information to the user as well. For styling, I think underlining the `year` and making it clickable to show a little component that displays the options is a good idea. Defaulting to the `month` is probably best since it provides a closer estimate of the current situation. I can pick this up if you don't mind. It'd be my first contribution to the dApp so I might need some help figuring some stuff out.

Sure, thanks 👍 If we go with option B, let's also just change the existing "year" text to "30 days" to match the default selectable option.

**Comment by staa99** [comment]
Hi @micahalcorn, 

I am having an issue running the dApp locally. I'm guessing the problem is from some missing ABIs. My branch is based on `master`.

![image](https://user-images.githubusercontent.com/20708724/175125133-8c358ff1-548d-4e7a-afe0-5b22a6e2c923.png)

![image](https://user-images.githubusercontent.com/20708724/175124652-0db4fa2b-fdfa-46e2-a735-d7e353bb20f6.png)

**Comment by staa99** [comment]
Hi @micahalcorn,

Just bringing this up in case you missed it. How do you think I can resolve this issue?

Thank you.

**Comment by rolandpo** [comment]
@staa99 I'd suggest dropping a message in the ousd-engineering channel on Discord if you're having trouble setting up your local env

**Comment by staa99** [comment]
Thanks @rolandpo.

**Comment by rolandpo** [comment]
done in #1033

**Comment by micahalcorn** [comment]
Reopening this per https://github.com/OriginProtocol/origin-dollar/pull/1033#issuecomment-1179311705 🙂
