### ISSUE TITLE
replace absurdly large numbers with error messages on insufficient liquidity

### ISSUE THREAD

**Issue by rolandpo** [OriginProtocol/origin-dollar#1047]
![image](https://user-images.githubusercontent.com/62400812/179523650-97308283-a6cc-4496-ab10-49ef167e759c.png)

**Comment by micahalcorn** [comment]
Thanks for filing this, @rolandpo. What threshold would you use to determine that it's insufficient?

**Comment by rolandpo** [comment]
I'm not sure about the exact number, but I think it would still be valuable to have as many options available to show liquidity levels, so even something like below 10% would be enough to get rid of these numbers overlapping

**Comment by micahalcorn** [comment]
> I'm not sure about the exact number, but I think it would still be valuable to have as many options available to show liquidity levels, so even something like below 10% would be enough to get rid of these numbers overlapping

This might be what you mean by 10%, but I was thinking that we should refrain from showing the numbers if your effective price is worse than $1.10. The only problem I can think of is that you can trigger a terrible price like that just by entering very low numbers (e.g. "1"). We wouldn't want to prevent those transactions since some people will do this to submit test transactions and kick the tires.

We actually already have a "slippage too high" state, which we could extend to include these high-price cases. In fact, I would probably just change that message to be "Price too high" since it's not exactly slippage in these cases.

Just for fun, here's the worst case resulting from low numbers (not as bad as your screenshot):

<img width="600" alt="Screen Shot 2022-07-19 at 9 04 02 PM" src="https://user-images.githubusercontent.com/273937/179894405-6271dbbc-ab98-4a28-beb8-d0f858e80244.png">

**Comment by rolandpo** [comment]
Maybe we could exclude routes where **Est. received** differs from input amount by more than 10% rather than **Effective Price**. That would be pretty much same thing for larger amounts, but wouldn't affect smaller test transactions

**Comment by micahalcorn** [comment]
> Maybe we could exclude routes where **Est. received** differs from input amount by more than 10% rather than **Effective Price**. That would be pretty much same thing for larger amounts, but wouldn't affect smaller test transactions

Smart 🧠
