### ISSUE TITLE
Agree on new yield-earning strategy

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1056]
It's safe to say at this point that we need to launch an additional strategy to raise the APY from current levels to something more competitive. We won't ship a new strategy just for the sake of doing it, but we will if it is safe and likely to have a meaningful, positive impact on our APY. Let's plan to agree on which strategy we'll implement and have a rough plan for how it will be engineered by end of Sprint 32.

**Comment by sparrowDom** [comment]
for info: OUSD Convex APR is pretty low right now (Metapool considerations)
<img width="1238" alt="Screenshot 2022-08-03 at 15 14 03" src="https://user-images.githubusercontent.com/579910/182617151-6adda716-d8c4-4d94-a802-12b726e14b2d.png">

**Comment by sparrowDom** [comment]
@micahalcorn has been mentioning Frax+3Crv somewhere. They had a pretty compelling 7% Convex APY - currently still sitting at 5.4%.  I am looking at 3crv + another coin Convex APYs: 
![convex](https://user-images.githubusercontent.com/579910/182691966-945294ca-9559-495f-b754-f52d7b89720c.png)

What I really like that for all these pools we can write a one single strategy (Solidity class) that we can reuse and would cover **all these pools**. No additional coding except governance action to deploy strategy / move funds is required. The strategy would share 90% of the code that we already have in place for the OUSD Meta Strategy. It is something I am confident I can code up this sprint. The strategy would: 
- deposit one of the stablecoins to 3Crv Curve pool to get 3crvLP
- deposit those 3crvLP into whichever metapool to receive the metapool LP ( e.g. Frax + 3crv)
- earn yield moneys
- when withdrawing we withdraw in a balanced manner -> get 3crv + other coin LP
- and swap whatever other LP coin we get for 3crv on the pool. 
- withdraw liquidity from 3crv pool for stablecoin

our vault never holds any other coins (e.g. Frax) since we always withdraw only 3crv liquidity. Good to keep in mind that while the strategy has funds deployed it is exposed to risk of the other non 3crv coin. And we wouldn't be earning double the APY as with OUSD metastrategy of course. 

thinking: Would be cool if there were TVL oracles. So we could implement a panic withdrawal function that wouldn't require governance vote. And would be able to withdraw funds when certain conditions are met. For example when TVL or Price of the other non 3crv coin changes too much.

**Comment by micahalcorn** [comment]
> What I really like that for all these pools we can write a one single strategy (Solidity class) that we can reuse and would cover **all these pools**. No additional coding except governance action to deploy strategy / move funds is required. The strategy would share 90% of the code that we already have in place for the OUSD Meta Strategy.

Yes, thanks @sparrowDom 👍 This is what I've suggested a couple of months ago as a generalized Convex strategy. We started to discuss it a bit in [the candidate strategies doc](https://docs.google.com/document/d/18h4x5ea_xVVn_aEMMnRuJJ4qDIzXzib1MWO0Y_3p3dY/edit#heading=h.l4un921cn0y9).

I like the idea of only ever holding 3crv or factory LP directly instead of allowing users to mint OUSD using X stablecoin. For analytics and transparency purposes, I think we would still want to depict the vault as "holding FRAX", for example, but we don't need to go so far as to promote it equally with DAI in our marketing. Maybe later we decide to officially support one of these as minting collateral and then we could stop swapping out of it when exiting a strategy.

I've been watching these pools regularly during the past few months of post-UST drama. They jockey for highest CVX rewards every two weeks, and the yields overall were down for a while due to the CVX price taking a big hit. As a group, they've recovered nicely and it always seems like there's one in the upper single digits that we _may_ be willing to dip into.

I'd love to confirm the scope of what you've described above and do a deeper dive on 2-3 of the pools to confirm that there aren't any surprises. While it will be great to have the framework in place to dip into a variety of emerging pools over time, we're likely to only really use one or two of them in the near future. We'll want to thoroughly audit each stablecoin that we get exposure to, and that will take time.

**Comment by sparrowDom** [comment]
Hah sorry missed that @micahalcorn. Didn't want to steal your ⛈️

Cool we have 1:1 today and we can discuss it. But generally any 3crv + token Curve pool is a Metapool that is running on the same code and has the same APIs as the 3CRV + OUSD pool that I have been looking into for the purposes of Metastrategy. Which means there is a unified way we interact with it

**Comment by micahalcorn** [comment]
Closing this since we've already made progress on the generalized Convex strategy 🎊
