### ISSUE TITLE
JSON-RPC requests

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin-dollar#240]
The amount JSON-RPC requests are.. intense.  Not sure where they're coming from, but requests for network ID and other trivial things are sent very often that it could actually DoS the client.  Should probably dial that back a bit.

Will fill out more detail when I have it.

**Comment by mikeshultz** [comment]
Seems to be OUSD price checks(probalby for the running total) and `eth_chainId` calls happening every less-than-a-second.

    {"method":"eth_chainId","params":[],"id":48,"jsonrpc":"2.0"}


    {"method":"eth_call","params":[{"to":"0x277e80f3e14e7fb3fc40a9d6184088e0241034bd","data":"0x686b37ca000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000045553445400000000000000000000000000000000000000000000000000000000"},"latest"],"id":49,"jsonrpc":"2.0"}


    {"method":"eth_call","params":[{"to":"0x277e80f3e14e7fb3fc40a9d6184088e0241034bd","data":"0x29a903ec000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000045553445400000000000000000000000000000000000000000000000000000000"},"latest"],"id":51,"jsonrpc":"2.0"}

**Comment by mikeshultz** [comment]
Every 5 seconds...

https://github.com/OriginProtocol/origin-dollar/blob/ce3c0f0a4d2ad5a01053e44d162339c73901a05a/dapp/src/components/AccountListener.js#L131-L133

...it loads the balance and allowance of of every relevant token.

https://github.com/OriginProtocol/origin-dollar/blob/ce3c0f0a4d2ad5a01053e44d162339c73901a05a/dapp/src/components/AccountListener.js#L24-L103

I suspect the `eth_chainId` calls are internal to ethersjs.

**Comment by mikeshultz** [comment]
@micahalcorn I think this might be a bit of a product decision.  We're getting a lot of rate limited requests from Alchemy, so this has to change, but it changes how the app operates.  Right now the app expects to see added tokens transfer in(and approvals) within 5sec.  

I don't know if we want to jack up the interval timing and add a manual refresh button?  Could change it drastically, even, and only do this update during a deposit phase and hide the deposit form when not in use (this allows the dapp to stop looking for allowances and balances as often)

I'm going to put in a PR to bump this to I think 15s right now for some minor improvement since there's not much of a point in checking more often than the block time.  But I think we should go further, and also maybe have the interval stop after like 30 minutes.  Not sure we want it to run continuously?

Or we could just own it and get Alchemy to raise the limit significantly.  :shrug: 

CC @sparrowDom @shahthepro

**Comment by mikeshultz** [comment]
Added PR #247 as a stop-gap but I'm guessing product isn't gonna be super happy with it.

**Comment by joshfraser** [comment]
What if we dynamically updated the refresh rate based on when you last interacted with the page?

If you've moved your mouse or interacted with the page in some way, you can have a super-fast refresh rate (every 1 second should be fine). Otherwise, we can drop you down to a significantly slower refresh rate (say 10 mins) refresh rate for people who leave their tabs open.

**Comment by micahalcorn** [comment]
Thanks @mikeshultz for raising this issue. Here's what we concluded during today's meeting:

- [ ] The APY calculation doesn't need to update regularly after page load. It can be stale until the user refreshes the page. If it's not too much trouble, it would be nice to refresh the APY when the user submits a transaction since that won't happen very frequently.
- [ ] The balance updates should taper off as the user stops interacting with the page. Maybe we can listen for mouse movements, as @joshfraser suggests above, or some other measure of user interaction. But even when we stop polling for the actual balance, the displayed balance should continue to climb optimistically based on the "current" APY.

@sparrowDom do you want to take a stab at this?

**Comment by sparrowDom** [comment]
Sure happy to do that

**Comment by sparrowDom** [comment]
PR for the last comment ( ☝️ ) from @micahalcorn here: https://github.com/OriginProtocol/origin-dollar/pull/251
