### ISSUE TITLE
Curve Strategy

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#253]
Add a vault strategy that takes stablecoin deposits and supplies them to [a Curve pool](https://www.curve.fi/). Unlike https://github.com/OriginProtocol/origin-dollar/issues/252, this won't require as much complexity for allocation since we can deposit and withdraw any combination of 1-4 stablecoins on Curve. We know from @DanielVF's research that we should not supply any DAI to Curve. However, we need to account for the fact that there are penalties and bonuses when you deposit or withdraw a single stablecoin or a mix of them that is substantially different from the currency pool allocation.

We will also need to decide with pool we want to use. They all function differently and involve different underlying contract risk. They also come with different levels of CRV rewards.

**Comment by matthewliu** [comment]
I think the two pools we should consider are the 3-pool which Curve is betting on themselves (https://resources.curve.fi/guides/depositing/depositing-into-the-tri-pool) and the yPool which has been dependable and stable for a couple months now. APYs are falling across the board, but our objective here is to get to double digits fastly and safely. It doesn't have to be overly optimized (for now). Once we prove that OUSD is compelling at a double digit APY, then we can further optimize. Our hypothesis is that there will be much more interest once we graduate from 3%, even if we are not at the top of the range.

3-pool has some benefits of being more differentiated than Yearn, so that has some small bonus points.

**Comment by tomlinton** [comment]
#306
