### ISSUE TITLE
Handle Dropped & Replaced Transactions

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#259]
If a user decides to "speed up" her transaction by submitting a second one with the same none and a higher gas price, our DApp is unaware of the new transaction and gets stuck waiting for the old one. This is a common problem with no simple solution yet.

See the following:
- [EIP 2831](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2831.md)
- [EIP discussion](https://ethereum-magicians.org/t/eip-2831-transaction-replacement-message-type/4448)
- https://github.com/ethereum/web3.js/issues/3585

**Comment by joshfraser** [comment]
In the meantime...

Until the transaction is confirmed, we could continue watching the blockchain for additional transactions that are signed by the original wallet & see if they look like replacements. Doesn't seem too hard.

**Comment by sparrowDom** [comment]
From my research when a client wants to increase gas it creates another transactions with higher gas price and the same nonce. Now the problem is that the web3 browser / Metamask do not communicate this back to the Dapp. There are some proposed solutions (that Micah outlined above) but nothing we could use today.

I see 2 ways we could get this done:
1. **slower way** - develop a backend that listens to the blockchain for all events / transactions on OUSD contract and expose that data via API. We could use @DanielVF  's `debug.ousd.com` for that, or fork it and develop a separate service. We need a similar service anyway to display all the debug information that were once part of the DApp designs.
2. **faster way** - use Etherscan API and pass the api key to the client to fetch all the transactions of an account. And see if there is a transaction that has replace the initial mint/redeem/allow one.

Personally I think the option 2 is not so messy and doable relatively quickly and would vote for that one if we want to have this functionality reasonably quickly. Actually I see that Etherscan allows 1 request every 5 seconds [to their api](https://api.etherscan.io/api?module=account&action=txlist&address=0xFD9E6005187F448957a0972a7d0C0A6dA2911236&startblock=0&endblock=99999999&sort=desc) without the need for an API key. That is more than enough to get the latest 20 transactions of an account and check for possible gas price upgrade transaction.

**Comment by shahthepro** [comment]
I would suggest to subscribe to new transactions using WS provider and adding a `from` filter instead of polling though.

**Comment by sparrowDom** [comment]
That might be even more elegant, thanks @shahthepro !

**Comment by sparrowDom** [comment]
PR for this issue: https://github.com/OriginProtocol/origin-dollar/pull/304

**Comment by micahalcorn** [comment]
@kayyoo23 reported that her replacement transaction for token allowance was not picked up. Was the fix in #304 intended to handle these too or just mints and redeems?
