### ISSUE TITLE
Sticky, Linkable Language Selection

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#260]
If a user selects a language other than English and then refreshes the DApp, her selection is lost. We also should be able to link to a particular non-English version. On the [website](https://github.com/OriginProtocol/origin-website/), we handle both of these cases by supporting a locale param in the URL.

**Comment by topoface** [comment]
@micahalcorn 
I am sorry, would you please give me the link to the DApp you mentioned?

**Comment by topoface** [comment]
@micahalcorn 
>If a user selects a language other than English and then refreshes the DApp, her selection is lost.
This is fixed but can't make a PR because I have no write permission.
>We also should be able to link to a particular non-English version.
I am not sure why `fbt-runtime` is chosen for this, I don't see the possibility that we can perform the above unless we use next-i18n or others.

**Comment by topoface** [comment]
@micahalcorn Would you please check this PR?
https://github.com/OriginProtocol/origin-dollar/pull/583
A simple fix.

**Comment by micahalcorn** [comment]
Thanks, we probably inherited fbt-runtime from our pre-Next days. @sparrowDom might have some opinions on how it compares to next-i18n.

**Comment by sparrowDom** [comment]
yup exactly like @micahalcorn says we've inherited that from previous projects and it is not really the ideal tool. Especially because of the lack of server side translations and as mentioned linking to a specific language.

It would be great to transition to  `next-i18n`. This probably involves: 
- combing over the project and migrating all source files with translation strings
- modifying Crowdin scripts that: 
  - push new translation strings to Crowdin
  - pull translated strings from Crowdin

**Comment by topoface** [comment]
@sparrowDom 
So you want transition, okay!
I will take care of it.

**Comment by sparrowDom** [comment]
@topoface you rock 🎸  ! Thank you
