### ISSUE TITLE
Out of gas Mint transaction failures

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#261]
We had an instance of a tx that failed with our current hardcoded limit:

- https://etherscan.io/tx/0xf9aeea5ea4dd7a9974cb2a506dab84deea82eb3968d7938680f4ee0f5eea860b
- https://majorhammers.com/tx/debug/0xf9aeea5ea4dd7a9974cb2a506dab84deea82eb3968d7938680f4ee0f5eea860b

This is was a mintMultiple with 2 coins (DAI, USDT).
We calculated 300k gas = MINT_SIMPLE_GAS_LIMIT + MINT_PER_COIN_GAS_INCREASE * 1

I was able to reproduce myself in this tx: <https://etherscan.io/tx/0x4c8127efdc38fbb19d0a16fb0ca796f703d34c97139f27f5317dfbec9c33036d>

I raise manually the gas limit to 400k and my tx succeeded. It ended up using 384,003gas:
https://etherscan.io/tx/0x2ccd001490b43b72559fc844e33440836c287b0ba34a3af921621ed669b4d7e8

**Comment by franckc** [comment]
I also did a mint with 3 coins and it used 430,094gas
https://etherscan.io/tx/0x7192d600d65dbfe18ee6dee76ed2665ee15bba4bbd3f78e61927d91a39ccddb2

**Comment by franckc** [comment]
I did a mint with (USDC, USDT) and it used 400,187gas
https://etherscan.io/tx/0x8ab8ccb01b3536fff9a1762b3317e731dc9cecaa89c140d9740eb8886a9847da

**Comment by franckc** [comment]
Based on the data above, I'd suggest we set the Mint gas limit to:
 - 1 coin: 200k
 - 2 coins: 420k
 - 3 coins: 450k

CC @sparrowDom @DanielVF

**Comment by DanielVF** [comment]
I'm really surprised that minting 3 coins could be so close to two coins in gas usage.

![image](https://user-images.githubusercontent.com/837/94426166-2a675980-015b-11eb-9b8a-eb1eea074595.png)

Looks like when mint multiple is called, it aways oracles all three gas prices, which is where most of our cost is.

![image](https://user-images.githubusercontent.com/837/94426855-34d62300-015c-11eb-87b3-5a8e6ec89621.png)

I've marked this as a P0, since we are currently broken for mint simple multiples right now.

Rather than one value for additional coins, we apparently need to have something that increases the values according to the number of coins in a mint.

**Comment by sparrowDom** [comment]
solution suggested by @franckc and fine tuned by @DanielVF in this PR: https://github.com/OriginProtocol/origin-dollar/pull/267

**Comment by sparrowDom** [comment]
Closed via: https://github.com/OriginProtocol/origin-dollar/pull/267
