### ISSUE TITLE
convience bool is expensive in storage, might not be worth it

### ISSUE THREAD

**Issue by fxfactorial** [OriginProtocol/origin-dollar#287]
in `OpenUniswapOracle.sol`

we have 

```solidity
    struct SwapConfig {
        bool ethOnFirst; // whether the weth is the first in pair
        address swap; // address of the uniswap pair
        uint256 blockTimestampLast;
        uint256 latestBlockTimestampLast;
        uint256 priceCumulativeLast;
        uint256 latestPriceCumulativeLast;
        uint256 baseUnit;
    }
```

this first value of bool is useful for the developer - but it is very costly in terms of storage, eating up a full word for a value of true or false 

also - this value is always derivable in uniswap pairs, one just compares the addr order of weth with the other token addr 

so i don't think the developer convience outweighs the storage costs

**Comment by joshfraser** [comment]
It's worth noting that the Uniswap oracle isn't currently being used.

**Comment by DanielVF** [comment]
I think this bool is only written once per oracle for the lifetime of the oracle in the contract. So it's not costing us ongoing money.

However, I think it's actually not an extra storage slot. A bool needs one bit, which rolls up to one byte. An address is 20 bytes. Since two are next to each other in the variables, they fit together into the same slot. 

I made a test contract on etherscan to verify this:

```
contract DebugSlotStuff {
    struct SwapConfig {
        bool ethOnFirst; // whether the weth is the first in pair
        address swap; // address of the uniswap pair
    }
    
    SwapConfig public config;
    
    constructor() public{
        config.ethOnFirst = true;
        config.swap = 0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86;
    }
    
    function toggle() public {
        config.ethOnFirst = ! config.ethOnFirst;
    }
}
```

The bool and the address share the same slot:

![image](https://user-images.githubusercontent.com/837/95749061-fadf4380-0c68-11eb-9017-6b0b4b6fa64d.png)
