### ISSUE TITLE
Idea: have client read public view of oracle data

### ISSUE THREAD

**Issue by fxfactorial** [OriginProtocol/origin-dollar#299]
not fully fleshed out - but one idea was having was to have client code use a view to read an oracle price from our contracts - included in the view code would be a hash using the block number / or timestamp. 

client then uses this data included in their call to redeem, which is a transaction, and they EIP712 sign on it, the contract is able to verify that input data came from the contract within an acceptable window of current block time. 

Admittedly not fully thought out and quite a bit of moving pieces - will update as get examples or invalidate the idea

**Comment by DanielVF** [comment]
Does the client's signature help us? They could be signing malicious data, and checking their signature would not prove that the data itself was good.

If our contract could somehow return oracle results with our own signature over those results, that would seem to be what would be needed. But I don't know enough to know how a contract with all open data could sign anything? Is this possible?

Another concern would be the being valid for a window of time. This would seem to allow a user to trade at their option using prices from the past. Letting your counterparty  at will use past prices is a good way to [get rekt](https://en.wikipedia.org/wiki/Max-Herv%C3%A9_George). I think our current oracle with no-crossing limits would keep this from allowing draining, but still feels like it just might exploitable somewhere someday.

Given that blockchain transactions can often take a half hour to settle, that means that even with a half hour window, we could still be throwing some number of transactions that would otherwise have worked.

**Comment by DanielVF** [comment]
👋 @ @fxfactorial
