### ISSUE TITLE
Proposal to remove allocate

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin-dollar#339]
I think our recent strategy implementations are showing that automatically allocating funds to strategies is difficult, particularly given requirements of things like Uniswap where equal amounts of two tokens are required. It's worth discussing whether we remove the automatic allocate from the Vault and handle it all manually. This ties in with #323. I'm envisioning a framework that the `strategist` role falls in, where it is (ideally) impossible for them to do anything malicious because they can only move funds between preapproved strategies and addresses.

**Advantages**

- Reduced gas costs for users.
- Much more flexibility in the way we move funds around, things like Uniswap are no longer a problem. Our strategies can be more complex.
- Can build a UI for reallocating funds that'll give us much more insight into what we are doing, e.g. we can display slippage from Curve, etc. I'm thinking something similar to @DanielVF's playground.
- It's interesting from the point of community participation. Our community could propose reallocation of funds via the same UI (without write access of course, but perhaps some way to record the actions and result).
- We'd still need to support unwinding of strategies in the case of a large redeem for OUSD, but the complexity of the Vault goes way down on the allocate/deposit side.

**Disadvantages**

- Funds will sit idle for longer periods.
- We need to find a way to reimburse the strategist for gas costs, probably via a fee (we do already have this problem though, as we are often calling required methods ourselves).
- More hands on.

**Comment by joshfraser** [comment]
In regards to funds sitting idle, we could have a default strategy that holds the funds until a strategist has a chance to rebalance things. For example, we could choose to hold everything in Compound or Aave until it's worth rebalancing.

If we go down this path, we should figure out how we can do it in a decentralized way. From a regulatory perspective, it's important that we're just writing code & not working as active fund managers. The more we can hand over control to the community, the better. This is in line with our long-term intentions anyway.

**Comment by tomlinton** [comment]
Recording what I/we discussed in Discord here:

- The UI could queue up the required method calls via governance to perform the fund reallocation (in the short term the method calls could just execute immediately).
- Ideally this would be via a short timelock or some mechanism where it'll pass automatically unless voted against.

It'd be great for community participation, there isn't that many things to govern long term.

**Comment by franckc** [comment]
Thanks for starting that discussion - it's important we figure this out.

A few thoughts:
 - Totally agreed that community participation would be great. Having a "governance UI" that makes it easy to understand how the capital gets allocated would be super helpful. Especially as there are caveats related to re-allocation due to withdrawal fees, slippage,  strategy with constraints (uniswap requiring equal amount of 2 assets). etc... Having a place to model all that would be great.
 - I do think though that having to make those capital allocation decisions too frequently is not optimal. I personally like better a model where the community votes for percentages to allocate to each strategies and those targets are used until a new proposal gets approved. This is very similar to how people are used to manage their stocks portfolio. You decide on targets every now and then (typically every quarter in the fiat world, but for crypto it should be more frequent) and then you execute the strategy until next review of your portfolio. 
 - The uniswap strategy makes things more complex due to the fact that it deals with 2 assets. And Solidity makes it a pain to implement any sort of advanced logic, especially since sorting is not supported. A possibility would be to do the heavy lifting pre-computation off-chain and feed a digest of it to the vault. I can't really come up with a super flexible way to represent the digest and for the contract to use it given the dynamic nature of the problem (balances in the various strategies change). But a limited (but perhaps sufficient) way to do it would be to generate for each asset type an ordered list of strategies to consider allocating the available assets, with a target percentage. For example: DAI: [ (S1, 10%), (S4, 90%) ]; USDT: [ (S5, 100%)]; USDC: [ (S3: 50%), (S2: 50%)]. The vault allocate method would loop thru each asset, loop thru each strategy in the list, check the strategy current % and pre-conditions (for uniswap for example that would be that enough asset available to allocate for both token0 and token1), then allocate.
 - Regarding when/how allocate gets called, our current solution of calling it on large mints does not bother me too much since only users depositing a large amount will pay for that gas.

**Comment by tomlinton** [comment]
> I do think though that having to make those capital allocation decisions too frequently is not optimal. I personally like better a model where the community votes for percentages to allocate to each strategies and those targets are used until a new proposal gets approved. This is very similar to how people are used to manage their stocks portfolio. You decide on targets every now and then (typically every quarter in the fiat world, but for crypto it should be more frequent) and then you execute the strategy until next review of your portfolio.

This is essentially what we have now (that is in need of a few fixes from https://github.com/OriginProtocol/origin-dollar/pull/336). Setting strategy weights is a governance call.

> The uniswap strategy makes things more complex due to the fact that it deals with 2 assets. And Solidity makes it a pain to implement any sort of advanced logic, especially since sorting is not supported. A possibility would be to do the heavy lifting pre-computation off-chain and feed a digest of it to the vault. I can't really come up with a super flexible way to represent the digest and for the contract to use it given the dynamic nature of the problem (balances in the various strategies change). A limited (but perhaps sufficient) way to do it would be to generate for each asset type an ordered list of strategies to consider allocating the available assets, with a target percentage. For example: DAI: [ (S1, 10%), (S4, 90%) ]; USDT: [ (S5, 100%)]; USDC: [ (S3: 50%), (S2: 50%)]. The vault allocate method would loop thru each asset, loop thru each strategy in the list, check the strategy current % and pre-conditions (for uniswap for example that would be that enough asset available to allocate for both token0 and token1), then allocate.

This is nicer than the current weight per strategy arrangement because it includes the weight per asset per strategy. My concern with this is that it is a) hard to implement and b) requires a complete liquidation and reallocation to get meaningful amounts of money into something like the new Uniswap strategy. E.g. we can't proceed with deposits of a couple of thousand USDC then later a couple of thousand DAI and expect to ever allocate to Uniswap given the preconditions. In general I think minters will generally only use one stablecoin so the logic of "keep this stablecoin on the Vault and wait until we have a matching amount of this other stablecoin and only then add it to Uniswap" is tricky.

I do think this would be an optimal solution if we can think of a way to implement it.

**Comment by franckc** [comment]
Yeah, Uniswap is tricky :( Couple more thoughts:
 - Currently allocate is only called on large mints. I don't know what the distribution of mint amounts will be like... but I assume that when a large mint comes in, there will be other stable coins in the buffer due to the small mints and that we could use that for allocating to the uniswap strategy.
 - Agreed that it will be unlikely the overall allocation of funds will match the "portfolio targets" organically. Perhaps as part of setting new targets we could liquidate some amounts from the strategies. That would be part of the governance decision. So that the first time an allocate runs with the new targets, there is plenty of capital in the buffer and we are more likely to match the defined percentage targets for strategies.

**Comment by DanielVF** [comment]
I'm wondering if it might be better to move the allocation logic outside of the vault to some kind of allocator contract. We,  then the community, set parameters on the allocation contract, and then it does the actual deciding. By having a separate contract, it's way easier to update the both the logic and the storage behind the logic.

One thing we've not really had is the idea of rebalancing. Often we would want to withdraw funds from one strat in order to place them in another, and this should be an atomic thing. 

I also think we need to move from allocating one coin at a time, to thinking in terms of "moving" multiple coins to the strategy at a time, then letting the strategy work with all the coins it has in the deposit action. This solves both the uniswap / mm case, could give us efficiencies with things like 3pool.

It seems like we may want to decouple our redeem logic from our allocate logic. If we have a strategy with an exit fee, most of the time we probably don't want to be withdrawing from it first for our redeems. We probably want this redeem logic to live in the allocator contract as well, and have it also not work one coin at a time, so that we can efficiently pull out of uniswap-like contacts.

One of the dangers of community driven allocations is that someone could call the execute on our reallocation in the middle of their own transaction, allowing them to both front-run us and close their position afterwords on the same transaction. This could be very bad. I think a way around this is to not view changes in allocation as single transaction changes, but rather "ramp" into new positions over time. For example, if we could set a one week ramp on a major change, and new funds would automatically be flowing into the the new strategies, redeems would be coming out of the old strategies, and our periodic rebalances would be be transferring much smaller amounts of funds.

**Comment by micahalcorn** [comment]
Related: https://github.com/OriginProtocol/origin-dollar/issues/42

**Comment by tomlinton** [comment]
In general it sounds like people are in favour of keeping the allocate method and updating the logic for allocates/redeems. I'm still of the view we should do it manually. I agree that it is preferable to keep it automatic but I think it is too complex to implement. 

We do need to move forward with one of these approaches though, it has consequences for a lot of existing work (particularly around what @fxfactorial is doing with Uniswap). Maybe we should enumerate the requirements in a separate issue and start thinking about a design.

Maybe one potential solution is based on the idea that no Strategy actually wants multiple tokens. Uniswap strategies want a single token (the LP token), our Curve strategies want 3Crv. We have additional logic in the strategies to get these tokens. There might be a solution around the Vault doing conversions but that also might just be more complexity.

@DanielVF the moving of assets between strategies is included as part of https://github.com/OriginProtocol/origin-dollar/issues/323, it should hopefully be fairly easy to do because you can specify a recipient when withdrawing from a strategy.

**Comment by DanielVF** [comment]
I guess the allocate question is kind of three different questions in one.

1. Who/what decides the overall allocation strategy
2. Who/what decides the individual fund moves
3. When does do these moves happen (and by extension, who pays the gas)

A super easy way would be:

1) There is no contract enforced allocations strategy
2) We make individual fund moves
3) We decouple this from mints, and do these as individual transactions.

I sure like the simplicity. My two concerns are that, we would be actively managing funds, and that decoupling allocates from mints means that we are probably moving bigger chunks of money at a time.

I think long term we want something like:

1) Allocation strategy comes from the community
2) Something contract level handles the details of reallocations
3) In general, gas for allocates/reallocates comes from whales's transactions.

Mixing the two a little, and running off what Josh said, we could just have a simple "default" allocation for each currency on mint. This could make the logic behind our mints super simple and much cheaper.

**Comment by tomlinton** [comment]
Closing this, will record decisions we reached on this in https://github.com/OriginProtocol/origin-dollar/issues/323.
