### ISSUE TITLE
Buffer-Aware Redeeming

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#343]
In my experience, it takes around `900000` additional gas to handle a `redeem` when the buffer is low and USDC needs to be withdrawn from the Curve strategy. [I recently updated the defaults to accommodate this](https://github.com/OriginProtocol/origin-dollar/commit/417f95403b0d80db2a0fe9ed59d1e30f601a7c95). But now we're setting a dramatically higher limit than we need when the buffer is sufficient. It would be nice for the DApp to be able to estimate whether or not the proposed transaction is likely to exhaust the buffer and dip into one or more strategies.

This could also tie in well with [the idea of the DApp intelligently routing transactions to Uniswap](https://github.com/OriginProtocol/origin-dollar/issues/110#issuecomment-683020209) instead of the vault when it's more beneficial.

**Comment by tomlinton** [comment]
Do we have a record of how far off the gas estimates are when we let it naturally estimate? We will always be playing whack-a-mole with these if we hardcode it, because every strategy has different gas requirements. I'm interested in finding out if the gas estimate has a systemic error (i.e. caused by the two delegatecalls), in which case it might be off by a fixed amount each time? I think a better way to do it might be get the estimate and add a buffer, e.g. estimate + 50,000 gwei or a percentage.

**Comment by micahalcorn** [comment]
@tomlinton I don't think we've had any naturally estimated limits since launch. Is it possible to run some estimates given a handful of scenarios and then let me compare those to actual gas usage in prior transactions?

**Comment by DanielVF** [comment]
You can call estimateGas on a transaction call with web3 to get the gas estimate back.

**Comment by micahalcorn** [comment]
Addressed by https://github.com/OriginProtocol/origin-dollar/pull/357 🤞
