### ISSUE TITLE
Public Credits Ratio

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#347]
Let's expose our `creditsPerToken` so that smart contracts can maintain an internal accounting of users' balances when they opt in to receiving yield post-https://github.com/OriginProtocol/origin-dollar/pull/335.

**Comment by franckc** [comment]
Actually rebasingCreditsPerToken is [already public](https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/contracts/token/OUSD.sol#L34).
So unless I'm mistaken we don't need to do anything additional work for the snow integration?

If I understand correctly here is what snow would need to do:
  - Pre-requisite: Have the snow contract call rebaseOptin()](https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/contracts/token/OUSD.sol#L402) in order to opt-in for ousd yield
  - When a user sends OUSD tokens to the snow staking contract, the contract should compute the number of OUSD credit deposited by the user and store that
```
numOusdCredits[address] = amount / ousd.rebasingCreditsPerToken()
```
  - When the user unstakes, the contract should compute the amount of OUSD tokens to send them back:
```
amount = numCredits[address]  * ousd.rebasingCreditsPerToken()
```

@tomlinton @DanielVF Did I miss anything?

**Comment by micahalcorn** [comment]
@franckc it looks like [that line was changed today](https://github.com/OriginProtocol/origin-dollar/blame/963dd86846b602c8b006fca8ba446e4f6fd35eff/contracts/contracts/token/OUSD.sol#L34) by @tomlinton after this issue was created, so he has picked it up. Thanks for enumerating what else there is for them to do.

**Comment by DanielVF** [comment]
That's how I think it should work @franckc. @micahalcorn, you going to email them?
