### ISSUE TITLE
CRV Vault Balance

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#352]
From what I understand, our vault is currently unaware of its CRV balance. Some comments from @tomlinton:

> [Call `integrate_fraction` on the Curve Gauge](https://etherscan.io/address/0xbFcF63294aD7105dEa65aA58F8AE5BE2D9d0952A#readContract) and enter the address of the 3pool strategy proxy (0x67023c56548BA15aD3542E65493311F19aDFdd6d or 0xe40e09cD6725E542001FcB900d9dfeA447B529C0).

> From messing with this and doing a harvest I discovered that `integrate_fraction` only counts up to the last checkpoint, so it could be a long way out of date. There is a `claimable_tokens` method that requires a write to update the checkpoint that would probably be more correct.

We should confirm what this means for our auto-harvest threshold.

**Comment by tomlinton** [comment]
The auto-harvest threshold won't work, it'll need to be set to 0 to make it always harvest. We could extend the strategy with a `rewardTokenBalance` method and do whatever work needs to be done to get the Strategy aware of the current balance.

I think it is probably OK to just always harvest the CRV though.

**Comment by franckc** [comment]
Is this issue still relevant now that we implemented the harvester @sparrowDom @tomlinton ?

**Comment by sparrowDom** [comment]
We are not doing any of the calls mentioned in the first comment. @tomlinton will know the specifics. I think it is still relevant

**Comment by tomlinton** [comment]
I think it is less of a concern now that the harvest function can be called by anyone and they are incentivised to figure out whether it is beneficial on their own (i.e. something to harvest). This issue was more for when harvesting was in the path of other functions like redeem and I wanted to avoid wasting gas calling harvest on Curve strategies when there was nothing to claim.

Since we've incentivised it I think we can close it.
