### ISSUE TITLE
Split OUSD Balance

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#362]
In our DApp, we currently show an estimated OUSD balance that is the combination of the on-chain wallet balance + an estimated increase based on the APY. This is has proven to be problematic for several reasons (see #275 and [this doc](https://docs.google.com/document/d/11KSaj7PWKfRaX81w2AZgeWH9CH9MaclIr8G9I-PNCFI/edit#)). We have decided to move away from this optimistic approximation and show two numbers instead: the on-chain wallet balance and the user's share of the pending rebase.

Here is a mockup of what it should look like: https://zpl.io/VDeKJ1g

There are several considerations involved in making this change:
- [x] Update the markup and styling to display two numbers, ~a collect link,~ and a help icon.
- [x] Remove the logic that currently calculates an estimated increase.
- [x] Remove [the logic that currently stores "animation progress" and maintains the optimism between refreshes](https://github.com/OriginProtocol/origin-dollar/pull/320).
- [x] Keep the "metering" logic in place so that the big number animates when the on-chain balance changes (immediately after mint, redeem, transfer, rebase, etc).
- [x] Monitor the pending rebase at every block by reading from the contract (possible inspiration starts [here](https://github.com/OriginProtocol/ousd-analytics/blob/master/eagleproject/core/views.py#L43)).
- [x] Animate the pending rebase every time it changes (approximately every 15 seconds).
- [x] Display a minimum of `0` when the pending rebase is negative.
- [x] Display "lorem ipsum" text when the help icon is clicked.
~Wire up the "collect" link to the vault's `rebase` function.~ Moved to https://github.com/OriginProtocol/origin-dollar/issues/364

**Comment by franckc** [comment]
We had a discussion on the engineering side and our recommendation was for the DApp to pull the rebase data by making an API call to the analytics service rather than by calling the blockchain. This is for 2 reasons:
  1. Reduce the overall volume of calls to our blockchain infrastructure provider (Alchemy)
  2. Centralize the code that computes the data rather than duplicating it in both the DApp and Analytics.

For computing the wallet's expected increase, the overall idea would be for the DApp to:
  - Get the number of credits for the account from the blockchain (by calling the creditsBalanceOf method)
  - Get the next projected creditsPerToken values from analytics
  - Calculate expected increase in OUSD as numCredits / creditsPerToken

Here are a few relevant pointers
 - Analytics API: http://analytics.ousd.com/api/v1/ratios and see code [here](https://github.com/OriginProtocol/ousd-analytics/blob/master/eagleproject/core/views.py#L138): 
 - The [creditsBalanceOf](https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/contracts/token/OUSD.sol#L100) method on the OUSD smart contract for getting an account's credits.

**Comment by sparrowDom** [comment]
Closing because this has been merged in today
