### ISSUE TITLE
More pause functionality

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin-dollar#395]
Do we want to have a system wide pause, i.e. all OUSD transfers, mints/redeems, rebasing, or some combination?

I'm inclined to expand our current deposit pause to also handle redeems. I don't think we need to go as far as pausing all OUSD functions (although Synthetix do so).

**Comment by joshfraser** [comment]
I'm on the fence with this one. It certainly would have been nice to have a pause-all button available after this hack.

Getting the permissions right is going to be tricky. For it to be useful, it needs to be quickly callable. It doesn't help much if the pause-function is stuck behind a multi-day timelock. But since it is so powerful, there need to be other safeguards to reassure people that it won't be abused by whoever holds those keys.

**Comment by tomlinton** [comment]
I think we'd go with the strategist role as the pauser, which would be a 2 of n multisig.

I'm leaning towards extending the pause deposit to cover redeem as well, but not going as far as a pause all. Any one else have any opinions?

**Comment by franckc** [comment]
+1 for giving the pause permission to the strategist.

Also it makes sense to me to have the pause applying to both mint and redeem.

Regarding the ability to pause transfers, it sure would have made easier for calculating the compensation numbers after this hack. But on the other hand it is a really big hammer and I could see our user community and our partners not liking it in the future.

CC @DanielVF @micahalcorn @crazybuster In case they have any opinion on this...

**Comment by micahalcorn** [comment]
I'm reluctant to pause transfers unless we have a really good reason to do it.

**Comment by DanielVF** [comment]
I don't think we should pause transfers. Too much power.

**Comment by tomlinton** [comment]
Ok, will extend the current deposit pausing to cover redeems and allocate in #428

**Comment by micahalcorn** [comment]
Considering this closed 🚪
