### ISSUE TITLE
Have some kind of maximum allowed difference, over which we do a negative rebase

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#399]
Note: This idea originated from the OUSD hack postmortem. Filing as a GH issue to have a discussion and make a decision on whether or not we want to implement this.

@joshfraser suggested having a threshold of  5% so that we smooth out daily fluctuations but do the right thing in case of a loss in the underlying assets.

CC @tomlinton @DanielVF @micahalcorn @crazybuster

**Comment by DanielVF** [comment]
I do feel like this could be quite useful as a way of keeping OUSD as stablecoin worth $1 after a problem, rather than having to make extremely painful decisions about how to apportion loses in order to get everything going again. 5% price change is still pretty big. We might might be able to do 2%.

**Comment by micahalcorn** [comment]
Do I understand correctly that we're currently still only doing positive rebases?

**Comment by DanielVF** [comment]
We are still only doing positive rebases.
