### ISSUE TITLE
Throttle redeems

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#401]
Note: This idea originated from the OUSD hack postmortem. Filing as a GH issue to have a discussion and make a decision on whether or not we want to implement this.

Possible value: 10% of total value per hour

CC @joshfraser  @tomlinton @DanielVF @micahalcorn @crazybuster

**Comment by DanielVF** [comment]
I certainly could see the use of this, but it feels like it would be complex and scary. How cleanly could we implement this?

**Comment by tomlinton** [comment]
I don't like limitations where users cant get their money out if they want it. It'd be good to keep it liquid as possible, and I'm concerned this type of feature may have impacts on the peg holding ability of OUSD. i.e. if the limit is reached, and a mass of people want to get out for whatever reason (even if its not hack related) we can crash the price on Uniswap/AMMs because its the only option for exiting OUSD.

**Comment by tomlinton** [comment]
Doesn't seem to be any strong positive feelings about this so will close, please reopen if you have further input!
