### ISSUE TITLE
Automated Rebalancing

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#42]
Once we are supporting multiple lending platforms and AMMs, we will want to regularly rebalance the pool to optimize for the best [risk-adjusted] yield-bearing opportunities. The two big questions to answer here are:

1. How should the contract determine the desired allocation (considering diversification, etc)?
2. What should trigger the rebalancing (on every mint/burn, for example)?

**Comment by micahalcorn** [comment]
What other parameters would we want to have here?

- Each strategy should get a maximum allocation so that we maintain some diversification.
- Each strategy should get a minimum allocation so that it continues to be in use.
- A lower threshold than our current auto-allocate might be necessary for this to be triggered on many mints or redeems.
- A profitability threshold should be included so that we're not unnecessarily reallocating in pursuit of a nominal increase in yield.

**Comment by DanielVF** [comment]
Complications here are that:

- Yield can change very rapidly. In the last week Compound USDT yield has more doubled or halved many times.
- We want to consider risk. If a Compound pool is offering max APY, there might be a reason for it. It means there is no liquidity, and there's a definitely chance that something has gone wrong somewhere, and any money put in could very well never come back.

When reallocating between only "safe" strategies that, it could be fine to have these called by the public.

Perhaps rather than putting all this gas expense into the mints/redeems, we could have mints and redeems put some money into a gas coin that can later be spent by the allocation calls.

**Comment by micahalcorn** [comment]
Replacing this with https://github.com/OriginProtocol/origin-dollar/issues/1308 ♻️
