### ISSUE TITLE
Rewards token transfer occurs on zero balance

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin-dollar#487]
Noticed that there were a lot of `RewardTokenCollected` events with a zero amount.  Looks like rewards token harvesting and ERC20 transfer appears to occur when it's unnecessary.  Haven't investigated them all, but my spot checks show it's probably from `allocate()` being called on `mint()`, which leads to `harvest()`

https://github.com/OriginProtocol/origin-dollar/blob/260ed61ab30c74cf55bb759480f3579d91d97bf4/contracts/contracts/vault/VaultAdmin.sol#L324

Which then tries to collect rewards and does a transfer regardless of balance.

https://github.com/OriginProtocol/origin-dollar/blob/260ed61ab30c74cf55bb759480f3579d91d97bf4/contracts/contracts/utils/InitializableAbstractStrategy.sol#L64-L69

Probably not a big deal, but could probably save some gas by checking a balance and only harvesting when it's worth it?  A zero transfer probably isn't worth an external contract call.  And dust probably isn't worth a uniswap swap.

**Comment by micahalcorn** [comment]
@tomlinton is this necessary because of the unknowable CRV balance on the 3pool strategy? I assume that these events were a symptom of us having the threshold set at 0 on Compound. Or is this something else that should remain open?

**Comment by tomlinton** [comment]
Yes, we don't know the CRV balance so it attempts it every time. Now we will have the same issue with Compound since governance removed that auto collect COMP.

- We could fix this by implementing methods on the strategies to determine there balance and changing the harvesting to call that.
- In the case of CRV (from memory) it requires a write to get an accurate balance as it updates a snapshot. I think the same call occurs automatically on a harvest anyway, so i'm not sure what will be more gas optimal. Checking and then harvesting if some balance, or just harvesting every time.
- I'm not sure what the situation for Compound.

Needs some further research.

**Comment by mikeshultz** [comment]
This is just a plain ERC20 transfer no?  Why is it unknowable?

**Comment by tomlinton** [comment]
Neither are plain ERC20 transfers, they require extra logic.

- 3pool requires a call to the 3crv minter with the address of the 3pool gauge from the strategy
- Compound requires claimComp on comptroller

After you do either of those they become plain ERC20 transfers.

**Comment by tomlinton** [comment]
From memory I think 3pool we can get a balance, it just might be a bit out of date, which might suffice for this.

**Comment by mikeshultz** [comment]
Ah, fair enough.  Reported this on code before COMP claims was implemented.  Guess this might be old now?

**Comment by franckc** [comment]
@sparrowDom Is this issue still relevant now that we implemented the harvester?

**Comment by sparrowDom** [comment]
I think we can close it for now. If people call harvest on Convex strategy with zero reward tokens available it is their loss. I assume this will not be happening anymore since there is no economic incentive.

**Comment by DanielVF** [comment]
Agree with closing for now.
