### ISSUE TITLE
Governance Fee Collection

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#527]
A few months ago, [we announced](https://medium.com/originprotocol/accruing-value-to-ogn-with-ousd-governance-and-protocol-fees-ef166702bcb8) that OGN would become the governance token of OUSD and that protocol fees would eventually accrue to OGN. We haven't decided yet how exactly those fees will accrue to OGN, but we are ready to start diverting some yield to a separate contract. We'll decide later what to do with those funds.

Here are some initial thoughts for V1:

1. We should start with at least one configurable variable to specify how much of the yield should be diverted to the new contract.
2. Would it be reasonable to have different percentages for different fees? For example, could the new contract receive x% of redemption fees and y% of strategy earnings?
3. The simplest implementation might be for the new contract to receive only OUSD by getting x% of each rebase. Otherwise, the contract would end up collecting a variety of stablecoins and governance rewards. Either way, we'll probably have to convert funds to a single currency whenever we put the funds to use in the future (accruing them to OGN). If the contract holds funds as OUSD, we can convert them internally instead of doing it with Uniswap when we're ready to use them.
4. If the contract accrues OUSD, we may or may not want it to opt in to yield.

**Comment by DanielVF** [comment]
For the MVP of this, I think we should purely work off the rebase yield. It's a very simple touch point, and works across every way yield is earned.

Two possible approaches off the top of my head:

1. When we are calculating a rebase, and see that have we would be increasing the supply by $1,000 we instead mint $200 OUSD (internal, via the OUSD contract) to the special contract address, and when we set the new supply, the actual increase is only $800. 

2.When we calculate a rebase, we first take the total vault value and subtract the amount stored in a governanceReserve  variable to get our new user facing vault value.  We add the new fee amount to the governanceReserve variable and subtract that new fee what we set the new supply amount too. In this way the governanceReserve amount increases on each rebase until collected. A special method on the vault can collect the governanceReserve amount in stablecoins from the vault and reset governanceReserve to zero.

Method 1. is very simple code. Hard to go wrong. The two disadvantages are that it's going to add maybe 100K-150K gas to every rebase (we keep on making rebasing cost more gas), and that we then have to convert out the OUSD afterwards, probably routing through on uniswap to get OGN.

Method 2. scares me slightly, since it a direct tap to vault assets. It is way cheaper on gas, only 30K additional gas per rebase. It would allow us to pick the exact coin we wanted which would make the fee using contract simpler.

**Comment by tomlinton** [comment]
Method 1!

Easy, elegant, and we can do it quickly for an MVP. Less clear on what to do with the OUSD after it is diverted though. Possibly initially buy OGN with it, then later just divert it directly to OGN stakers.

**Comment by franckc** [comment]
I'd vote for the simplest solution as well. Even if it increases the gas cost for rebases. I think that's an ok trade-off.

As to what to do with the OUSD collected in the "collector" account, that's a separate discussion. We can let the product/business team be creative.

In the long-term the "creator" could be a contract. With governance based voting so that OGN holders can decide what to do with the funds. In the short-term, I think we just setup a multi-sig controlled account and we manually handle whatever we want to do with the proceeds.

**Comment by joshfraser** [comment]
+1 for keeping it simple. Let's take X percentage of every rebase (where X can be easily configured in the future).

Instead of sending the funds off to another contract & just sitting there, I'd be a fan of having our contracts use the proceeds to buy some OGN on Uniswap. We already have the code for executing a trade on Uniswap, we just need to change to another pool and make sure there's enough liquidity there. We'll want to make sure this only happens every now and then (or when manually triggered) to save on gas. Maybe it's a function that only strategists can call?

My current thinking is that we'll use the OGN as a variable reward for OGN stakers at the end of their lockup.
