### ISSUE TITLE
Costs Disclaimer in Mint Experience

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#551]
We want to add a small reminder for users of our DApp to consider the costs associated with OUSD. We're transparent in our docs, but not everyone reads these before jumping in. We'll start by adding some text to the mint screen to encourage people to review the relevant concerns.

Desktop: [Zeplin mock](https://zpl.io/VDPD5Ol) (ping Discord for access)
Mobile: same as desktop but with the text above the mint button with maybe 15px margin in between

<img width="733" alt="Screen Shot 2021-02-08 at 4 49 46 PM" src="https://user-images.githubusercontent.com/273937/107300164-c8363380-6a2d-11eb-8765-ba1348349a03.png">

**Comment by sparrowDom** [comment]
Designs have updated a bit since this ticket was created 
<img width="1012" alt="Screenshot 2021-09-08 at 10 43 46" src="https://user-images.githubusercontent.com/579910/132476947-0b721d20-7b1b-488c-be9a-68b920c5ff03.png">

Imho costs are now pretty well described in transaction routing table. Should we repurpose this issue (or create a new one) for adding explanation question mark popovers in various locations in the dapp?

(latest Zeplin designs: https://zpl.io/2G5n6QJ)

**Comment by micahalcorn** [comment]
@sparrowDom my primary concern here was the exit fee. Users should expect to have to pay for gas and they're well aware of how costly it can be when it's in their face. Our interface also does a good job of communicating the slippage or exchange rate loss (depending on the route). But it doesn't tell the user that they're going to be upside-down on the transaction for some period of time. See https://github.com/OriginProtocol/origin-dollar/issues/92#issuecomment-701029761.

That said, this is much less of an issue if we have deep liquidity. With our current Uniswap depth, you can pretty much already swap 100k OUSD for stablecoins at a cost of .02% (gas included). It will get even better once we've driven exponentially more liquidity to Curve.

So yeah, I think we can probably close this and open a new one for the tooltips. As long as we have the exit fee covered in the documentation and plenty of liquidity on AMMs, then this is only relevant for enormous mints. Those users should be going through some due diligence if they plan to be able to redeem quickly.
