### ISSUE TITLE
Additional Noob Content on running the Node and dApp locally

### ISSUE THREAD

**Issue by cipherzzz** [OriginProtocol/origin-dollar#573]
**Description**:
Add additional content for running the dApp and node locally for a complete beginner.

- Node 14 is the highest engine allowed
- You may need to set your GA id in local.env to some dummy value
- Hardhat task to mint stablecoins - `HARDHAT_NETWORK=localhost npx hardhat fund --amount 1000`
- A local dashboard to mint coins within the UI for developers - http://localhost:3000/dashboard
- How to get a private key from the local node to import into your Metamask wallet 
- How to get the mnemonic if you want to create a whole new Metamask wallet

**Locations?**:
- https://github.com/OriginProtocol/origin-dollar/blob/master/README.md#running-local-node-using-hardhat-evm
- https://github.com/OriginProtocol/origin-dollar/blob/master/dapp/README.md

@franckc - there seem to be two references to getting things up and going both in the dApp and root. Do you want both updated?

**Comment by franckc** [comment]
@cypherzzz Awesome. Thanks for filing this and volunteering to update our docs! :)
A few thoughts:
 - I think we should consolidate all the instructions for starting the DApp in a single place. Otherwise if we have them both in the root README and in the /dapp README things will get out of sync. Maybe the root README links to the /dapp README? Feel free to suggest what seems best to you.
 - I added a fake value for GA_ID in [local.env](https://github.com/OriginProtocol/origin-dollar/blob/master/dapp/local.env#L34) as a stop gap solution. But I think it would be better if the server just handles gracefully an empty GA_ID and disables Google Analytics in that case. @sparrowDom do you agree?
 - I had some issue with my metamask (latest version 9.0.5 on firefox) not working due to hardhat using by default chainId 31337 (see [doc](https://hardhat.org/config/#hardhat-network)). I had to manually add a new metamask network. Probably worth documenting how to do that.

@sparrowDom can you think of anything else we should document?

**Comment by sparrowDom** [comment]
Sorry missed you comment @franckc. Agree on all points. @cypherzzz The easiest way to pass a fake GA_ID would be to do it here similarly as it was done for `MIXPANEL_ID`: https://github.com/OriginProtocol/origin-dollar/blob/master/dapp/src/utils/analytics.js

Maybe another useful thing to document would be running the dapp in production mode from the local machine. That is useful when you want to directly run it agains mainnet, or would like to test some feature of the production environment. For example to see if Google analytics is sending out the events.
- no need to run the node here
- user needs to decrypt production environment secrets. For that gcloud CLI configuration is requred. 
- then in the dapp folder: `yarn run build && yarn run start:production`

**Comment by sparrowDom** [comment]
@cipherzzz do you mind adding this stuff in?

**Comment by cipherzzz** [comment]
I’ll take a look today and let you know if I have any questions. Thanks!
