### ISSUE TITLE
Prototype for Keep3r integration

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#577]
Build a working prototype on the Kovan Testnet to integrate OUSD with Keep3r. See [announcement](https://andrecronje.medium.com/scaling-keep3r-with-chainlink-2832bbc76506) and [draft technical doc](https://docs.google.com/document/d/1btVxjEU0rhe2ZoUdLmeDUvezftD4Wkdb0VwFnuna3Is/edit?usp=sharing).

The idea is to have [allocate()](https://github.com/OriginProtocol/origin-dollar/blob/325bfa4e5a85d348caad36875aceed2ec0f9e55c/contracts/contracts/vault/VaultCore.sol#L264) and [rebase()](https://github.com/OriginProtocol/origin-dollar/blob/325bfa4e5a85d348caad36875aceed2ec0f9e55c/contracts/contracts/vault/VaultCore.sol#L361) called by Keep3r rather than based on logic running during users mint/redeem operations depending on [autoAllocateThreshold](https://github.com/OriginProtocol/origin-dollar/blob/325bfa4e5a85d348caad36875aceed2ec0f9e55c/contracts/contracts/vault/VaultAdmin.sol#L73) and [rebaseThreshold](https://github.com/OriginProtocol/origin-dollar/blob/325bfa4e5a85d348caad36875aceed2ec0f9e55c/contracts/contracts/vault/VaultAdmin.sol#L86).

This way the gas costs for calling allocate() and mint() would not be incurred by the users.

The exact logic for implementing the checkUpkeep() method is up for discussion. Perhaps the simplest implementation could check if the rebase and allocate thresholds have been crossed. 

A couple of notes:
  - We don't have a Kovan deployment for OUSD. We'll have to deploy our contracts on that Testnet. We have a Rinkeby deploy that uses mocks. Though the we had to modify the hardhat deployment to make it work (see [this branch](https://github.com/OriginProtocol/origin-dollar/tree/franck/rinkeby_deploy)).
  - It would be interesting to measure the gas savings
  - We should think about how the OUSD system would fund the `keeper`. Would this come out of the trustee fees?

**Comment by franckc** [comment]
CC @tomlinton @DanielVF @joshfraser @cipherzzz

**Comment by tomlinton** [comment]
Sounds great!

I think we'll need to adjust the rebase and allocate threshold logic since they are per deposit thresholds. We'd need to convert these over to measure the amount awaiting rebase and the amount in excess of the vault buffer we have. This is going to be the more complex bit, the actual integration with Keep3r looks reasonably straightforward.

The gas savings we can tell ahead of time from Tenderly, it has a really good gas profiler. From a recent transactions _rebase - 398,515 Gas and _allocate - 2,592,245 Gas.

Yes I think the logical place to fund the gas costs is from the trustee fees.

**Comment by joshfraser** [comment]
We'll need to decide whether we want to integrate with the original Keep3r project from Andre or focus on integrating with Chainlink Keepers. I haven't been following either project closely enough to have an opinion yet.

For context:
https://andrecronje.medium.com/scaling-keep3r-with-chainlink-2832bbc76506

@coleman415 may have thoughts from a business perspective.

**Comment by cipherzzz** [comment]
Tom/Josh/Daniel/Franck:
    Hello! Franck has assigned me to this project to see if there's mutual
fit on the team. I hope regardless of the outcome that I can be of help!
What is the best way to connect with you guys? Just ping you in discord or
email? I'm going to put some thoughts together this morning and reach out.
Thanks,
Mark

**Comment by joshfraser** [comment]
@cipherzzz looking forward to working with you. Discord works great for discussion. I'm Josh Fraser#1105.

**Comment by cipherzzz** [comment]
Had a quick sync with @DanielVF - let me know your collective thoughts: @joshfraser @franckc @tomlinton 
Assumptions
- Using the Chainlink implementation on Kovan - @joshfraser let me know if this changes based on discussions with @coleman415 
- Using a single contract as the proxy to the underlying vault contract and implementing keeper interfaces on this. UNLESS we want to put this into @tomlinton trustee contract
- Registering the maintained contract via smart contract rather than chainlink ui
- One shot funding of the keeper maintenance account for now - rather than automating the account balance of Link
- the registered contract will house both the rebase and allocate calls and call a combination of them based on the criteria we setup
- the rebase logic will be triggered by a magic number determined by comparing the vault amount and total supply of ousd
- the allocate logic will be triggered by a magic number of the vault tokens to be harvested

**Comment by tomlinton** [comment]
Yep sounds perfect. I think for now we'll just keep it as a separate contract rather than put it in the trustee. We could always modify that later though, it might make sense if we are using the trustee funds for the gas payments.

**Comment by cipherzzz** [comment]
Would these be the entry points for the `keeper` into the vault? 
https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/contracts/vault/VaultCore.sol#L361
https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/contracts/vault/VaultCore.sol#L264

It seems like the `keeper` would just need to interact with the `VaultCore` and we can tweak the parameters manually in `VaultAdmin`? @tomlinton @DanielVF

**Comment by cipherzzz** [comment]
I have the basic functionality in this PR: https://github.com/OriginProtocol/origin-dollar/pull/580

Outstanding Issues:
- Need to mock the VaultCode and OUSD contracts to run tests
- I need to figure out a way to get the `tx.origin == address(0)` to verify the `noExecute` decorator
- Do we have a contact at Chainlink that I can reach out to for integration? @franckc

**Comment by cipherzzz** [comment]
So... getting to the point of registering the `keeper` task with Kovan. Speaking with @DanielVF ,  he said that deploying the whole `origin-dollar` to Kovan would be a heavy lift. I am working on helper scripts to register the contract with the registry and fund it right now.  I feel like trying to deploy everything to Kovan would be out of my depth at this point... maybe that's an understatement. 😆  @tomlinton @franckc

**Comment by cipherzzz** [comment]
The `registerUpkeep` method on the `KeeperRegistry.sol` has an `onlyOwner` modifier. I'm guessing we can't register our own contracts with it.... unless I'm reading it wrong?
```function registerUpkeep(
    address target,
    uint32 gasLimit,
    address admin,
    bytes calldata checkData
  )
    external
    override
    onlyOwner()
    returns (
      uint256 id
    )```

**Comment by tomlinton** [comment]
Yep you are 100% correct. The integration on Kovan requires us to get Chainlink to add the upkeep. So I think in place of writing scripts to call those methods we just need the correct parameters to pass to them.
