### ISSUE TITLE
Improve connecting wallet UX on mobile

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#865]
This is still in a suggestion / work in progress phase type of issue: 

Visiting ousd.com from a mobile browser can be confusing. Wallet connection options and error messages when connecting the not supported wallets. If we were to copy Uniswap's approach we would: 

- show only the Wallet connect option when visiting with a mobile browser (No ledger / Metamask options)
- autoconnect to a wallet if using Metamask mobile browser
- on desktop behaviour is not changed. We should still change the "No Ethereum Wallet detected" to something that can not be confused with "There is no ethereum in your wallet"

**Comment by micahalcorn** [comment]
In my experience, MetaMask and Coinbase Wallet already skip the modal in their mobile browsers. So I don't think we would need to change anything there. I was also surprised to see that WalletConnect already works quite well from mobile Safari.

**Comment by micahalcorn** [comment]
Another option is to leave the buttons intact on mobile and just link to each vendor if there is no web3 on the window. So, for example, the MetaMask button would point to https://metamask.io in mobile Safari.

**Comment by franckc** [comment]
@micahalcorn Is it something we'd like to prioritize?

**Comment by micahalcorn** [comment]
Coinbase Wallet and WalletConnect work well for me. For MetaMask, I would look into [deeplinking](https://docs.metamask.io/guide/mobile-best-practices.html#deeplinking). If it's possible to detect that the user does not have a given app installed, then it would be nice to link to the app's website when the button is clicked. I don't think I would hide any buttons like Ledger just because it isn't supported on mobile. People often use these buttons as indicators of what we do support. So I would just prompt the user if she taps Ledger and say that it's not supported on phones. Otherwise, yes, these would be nice improvements.

**Comment by sparrowDom** [comment]
Agree, deeplinking would be a great addition, especially since some ( no idea how many) users are already used to it from the other apps. 
As for the issue of hiding unsupported wallets I would still show them but grey them out (make them seem disabled). We can still show the prompt as @micahalcorn suggests in case users click on them.

**Comment by rolandpo** [comment]
done in #1008
