### ISSUE TITLE
Stream rewards from harvests

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin-dollar#879]
We should consider [copying Convex](https://docs.convexfinance.com/convexfinance/faq/platform-rewards-current-vs-projected-apy) and stream the yield from harvests over 7 days. Basically, we would total up the reward token sales for the week, then evenly split them over the next week with our daily rebases. This would help smooth out the daily APY and make it harder for people to front-run any big harvests. We could always adjust the time period. but 7 days feels about right as a starting point.

**Comment by sparrowDom** [comment]
I like it definitely an improvement.

Another thing I am thinking, should we "cap" the amount of yield to a specific percentage? Let's say 20%? This way if there are daily/weekly yields higher than the cap the surplus would be stored and released in times of weaker APY. 

The goal to achieve would be that higher yield weeks / months would build up the reserves for more bearish times.

**Comment by joshfraser** [comment]
I'm always reticent to commit to any specific APY.  We're entirely at the mercy of macro conditions and I never want to give people the false impression that we're not.

If we were to implement a reserve, it would be nice to have it automatically adjust base on historical APYs instead of a fixed number. That might be too tricky or expensive to implement in a smart contract, but it makes a lot more sense than us picking some arbitrary number.

**Comment by DanielVF** [comment]
We could put a dripper contract between the seller contract and the vault.

The seller would turn funds into USDT, then send to the dripper. The dripper only has to deal with USDT. When the vault rebases, it would ask the dripper for all the unlocked funds.

When we calcuate the "next rebase" in the UI, or in analytics, we also use the unlocked funds from the dripper. Since some funds unlock every block, this means that the next rebase number steadily climbs.

<img width="508" alt="image" src="https://user-images.githubusercontent.com/837/149025717-f6580881-de2b-4c24-8f7c-5f1c2525f40d.png">

**Comment by joshfraser** [comment]
Wouldn't it be better if we deployed the funds right away and only the balance increases were delayed?

**Comment by DanielVF** [comment]
It would be better, but it's going to small in the grand scheme of things. Let's say our raw yield is 10% of total, we delay that by 1/100 of a year (half a week delay on average) so that 1/1,000 doesn't earn 10% yield, so that would make 1/10,000 a difference in the total yield.

Or did I get something wrong in there. :D

**Comment by joshfraser** [comment]
There could also be gas savings from moving the funds into an earning strategy 1 time instead of 7 times, no?

**Comment by DanielVF** [comment]
Yeah, could be gas savings there.

**Comment by micahalcorn** [comment]
> We should consider [copying Convex](https://docs.convexfinance.com/convexfinance/faq/platform-rewards-current-vs-projected-apy) and stream the yield from harvests over 7 days. Basically, we would total up the reward token sales for the week, then evenly split them over the next week with our daily rebases. This would help smooth out the daily APY and make it harder for people to front-run any big harvests. We could always adjust the time period. but 7 days feels about right as a starting point.

What happens when rebase is called outside of the daily schedule? Do we count the blocks since the last rebase and determine the amount of split based on how many blocks are expected within the rolling period (7 days)?

**Comment by sparrowDom** [comment]
> I'm always reticent to commit to any specific APY. We're entirely at the mercy of macro conditions and I never want to give people the false impression that we're not.

Agreed it would probably increase confusion too much. 

> Yeah, could be gas savings there.

It makes sense separating "dripper" logic from the vault, especially if we are going to change it often. Then again might make sense to measure what is the gas impact of that separation.

**Comment by joshfraser** [comment]
Gas costs are a major consideration. The Convex smart contracts have a lot of nice features, but they are quite expensive to run. Maybe there's a "dumb but cheap" way to do this?

**Comment by DanielVF** [comment]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/837/149203342-f7d33faa-4e0f-47c6-9fc3-343fe56c18b6.png">
