### ISSUE TITLE
Governance vote locking parameters

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin-dollar#886]
We need to determine the vote locking parameters for governance.

- From previous discussions I think we may have settled on 4 years as the maximum lock time.
- Allow EOAs only. Contracts need to be whitelisted.

Open questions

- Boost of vote locking at maximum vs unlocked.  I'll investigate what kind of curve other projects use. Default to whatever Curve uses.
- Do we want early unlocks of locked governance tokens for a fee?
- Do we want to take any steps to prevent token wrapping?

**Comment by sparrowDom** [comment]
Having a contract whitelist should be a strong deterrent for wrapping a voting token -> as long as we also support removing of the whitelisted contracts. Since un-whitelisting a contract could cause a disaster for the contract that has wrapped the token.

On the other hand if we do not support removing of whitelisted addresses that should remove risks for the wrapped token. In this case the whitelisted addresses should probably not be upgradeable. 

Curve and Convex have interesting relationship where the latter has removed much of the limitations of the former (non transferable voting token) + maximising the boost when holding veCRV + adding additional CVX reward token.

I am sure this serves as a nice psychological mind game, where there are certain project limitations. And then using blockchain money legos there is a solution that alleviates the limitations + adds new incentives. Wondering if original Curve token strategy would be as successful if the limitations wouldn't exist to begin with. 

I am not sure whether Curve is happy that governance has been pulled away from their platform and is managed on another completely. On the first glance it seems like a complete takeover. But when checking Curve's discord they have a #convex channel under their `General` channel section. They could also be happy having double boost on their platform, even though the second token isn't theirs.

If it proved to be beneficial for Curve to have a relationship with Convex, we should probably do as much as we can to enable something similar. (And do some more research as well)

**Comment by joshfraser** [comment]
Frax is an interesting case study. They copied the veToken model but initially only allowed EOA's and whitelisted smart contracts to vote-lock. Then they did a 180 and partnered with Convex! The short-term benefits are undeniable. Whether they risk losing control over their protocol long-term as a result is another question. 

https://frax.convexfinance.com/
https://convexfinance.medium.com/december-update-protocol-expansion-cvx-eth-incentive-migration-2c9327b48259#0a3b

**Comment by tomlinton** [comment]
Initial parameters I'm working with are:

Max lock time: 4 years
Min lock time: 1 week
Boost: 4x for max lock time

With vote power decaying linearly over the lifetime of the lockup.

I'm working with the OpenZeppelin [ERC20Votes contract](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.4.0/contracts/token/ERC20/extensions/ERC20Votes.sol) and modifying it to support lockups, which should hopefully allow us to build based on OpenZeppelin's governance system.

I'll probably go with a read only model similar to Curve (i.e. no ERC20 transfers), but delegation is supported.

The linear decay thing is quite a hard nut to crack, if we used a constant vote boost for the entire lockup period the contracts would be much simpler. This might allow voters with a lot of weight (a long lockup) nearing the end of the lockup to vote in a way that might not align with the long term interests of the project, as with the linear decay their voting power is reduced.

**Comment by franckc** [comment]
Doing some issue cleanup. I think we can close this on since the implementation is done.
