### ISSUE TITLE
Establish Rules for Flash Transactions

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#91]
Decide whether or not we will allow a single transaction to call our contract methods more than once, such as to mint and redeem tokens in the process of executing a flash loan. If this will be supported, add the framework for a fee, the amount of which can be established through a governance proposal.

**Comment by tomlinton** [comment]
Bumping this up in priority since we need to make a decision on it before the end of the week. Anyone have any thoughts? I'm inclined to implement a simple check that prevents mint/mintMultiple and redeem in the same block.

**Comment by joshfraser** [comment]
I'm okay with increasing the gas costs on mints & redeems. I'm more concerned about whether we can do this without increasing the costs of basic transfers as well.

Seems like we need to track transfers as well since an attacker could route funds through 1 or more wallets in between the mint and redeem.

**Comment by tomlinton** [comment]
Yea that is true, it'd need to prevent transfers and it'd come with that transfer cost which is a pretty big negative.

**Comment by nick** [comment]
Wouldn't a simple mint / redeem on the same block check prevent flash loans, though? Since with flash loans everything needs to happen on the same block?

**Comment by nick** [comment]
We could do this by having a `lastMintOrRedeemBlock` var that gets set to the current block number on `mint` and `redeem` methods. Each method checks that `lastMintOrRedeemBlock` is not already equal to the current block before proceeding. 

The downside would be an error thrown if 2 or more users happens to mint or redeem on the same block (which is fairly unlikely?)

One way to mitigate that slightly is to track lastMintBlock and lastRedeemBlock separately so that either multiple mints or multiple redeems can happen on the same block, but not both.

Personally I think the security benefits outweighs the inconvenience to users, especially if the error is explained: "Your transaction failed due to an OUSD security measure designed to protect your funds. Please try again".

**Comment by nick** [comment]
tagging @DanielVF as he's not on this thread yet

**Comment by joshfraser** [comment]
@nick i like the simplicity of what you're proposing, but i worry that we get some big press and have hundreds of people trying to mint at the same time. I hate the thought of them all having such a negative first experience with our product.

**Comment by micahalcorn** [comment]
Let's not remain in limbo on this issue. During last week's meeting, @DanielVF threw out some possible ways to protect the vault from flash loan risks:

- limit contract interactions per block (similar to @nick's proposal above)
- check known flash loan sources in every transaction (gas inefficient and unlikely to be effective)
- limit the size of mints (https://github.com/OriginProtocol/origin-dollar/issues/394)

**Comment by shahthepro** [comment]
> but i worry that we get some big press and have hundreds of people trying to mint at the same time.

@nick @joshfraser In that case, I guess the solution of using an address-to-block-number mapping should work. I've already mentioned that above https://github.com/OriginProtocol/origin-dollar/issues/91#issuecomment-688877666

**Comment by franckc** [comment]
@tomlinton kindly volunteered to do a further analysis of our options

**Comment by tomlinton** [comment]
Here is my attempt to summarise:

# General thoughts

In considering these options there are a few additional thoughts that are worth considering:

**Is there a legitimate need or use for OUSD to support flash loans?**

Yes. Flash loans are an enabler for mint/redeem based arbitrage on AMMs. For example, if OUSD falls below its peg significantly an enterprising individual could purchase a large amount using a flashloan, redeem it for stablecoins, and swap those back for the flashloaned currency to pay it of. This is also applicable to mints. Importantly, as OUSD grows, flash loans may become important for OUSD to maintain its peg.

**What is the response time of Governance to an exploit?**

It helps framing this argument to consider how long it'd take (on average) to mitigate an attack that was ongoing. 30 minutes seems like a reasonable timeframe, or approximately 120 blocks. This is considering the availability of signers and the multisig setup.

**Are flashloans a prerequisite for exploits?**

If flashloans are possible the pool of potential exploiters is wider. Without flashloans exploiters are limited to legitimate whales and illegitimate whales (aka hackers).

I don't believe the first group are much of a risk due to the difficulty of anonymising large amounts of funds and because they have legitimate opportunities to pursue.

The second group are a danger, they have access to significant capital and have already proven themselves to be the best at identifying and exploiting DeFi protocols. As time passes and more funds end up in the hands of the second group the protection offered by any solution here becomes less and less effective.

# Options

There were more ideas than the ones outlined below, but I haven't considered them as they were either deemed to be not possible or not worth considering due to the negative impact.

## Option 1: Limit size of mints and redeems (3 Votes)

This is the simplest thing we can do (if we are going to do something). The code complexity is low and the additional gas cost is minimal.

With lower limits (e.g. 500k) we run the risk of severely damaging composability and the way OUSD can be used in the DeFi ecosystem (ref the above example of OUSD returning to peg through arbitrage). With higher limits it quickly becomes ineffective when you consider how many transactions someone could fit into 120 blocks.

Something we haven't considered is that we already have some informal limits implemented. Some of our Strategies (Curve) are segregated, so that funds cannot flow in or out without Governance intervention. This is equivalent to a limit on the redeem side (provided funds get moved into these strategies). We might be able to leverage this to mitigate flashloan risk by keeping the bulk of the funds in segregated strategies. It is important to note the drawbacks around composability here when we consider how we are moving funds between strategies.

- Simple
- Minimal/no protection
- Composability consequences
- Already have some aspect of it implemented

## Option 2: Doing nothing (3 votes)

The simplest solution with the best composability properties.

## Option 3: Delay redeems above a certain size (4 votes)

This isn't a fully fleshed out idea but it may look like this:

- Large redeems (e.g. > 500k) result in the minting of an OUSD "Redeem Coupon" which is just another ERC20
- Some mechanism to track a timestamp at which these coupons can be redeemed for stablecoins

I can't think of the best implementation here, but it might be that the coupon ERC20 is unique to each redeem (e.g. OUSD-COUPON-03-04) which allows tracking of the redeem time. Or perhaps we maintain a mapping of addresses to redeem times and make the ERC20 non transferrable. I feel like this is a complex implementation and difficult to grasp from a usability perspective.

This seems to provide the best level of protection if we were to implement something as it won't allow the hacker to repay a flashloan in the same transaction or buys us time to mitigate if they are using their own funds. The limit is a difficult value to set because of the usability consequences, and if we set it too high the attacker might redeem right below the limit and an exploit might still be possible.

- Complex
- Gas costs
- Composability consequences
- Significant usability consequences

# Recommendation

My view is we do nothing, except use our segregated strategies to minimise risk while being cognisant of how that impacts composability. We should try to avoid a situation where the largest holder can't redeem because they can't be paid out in stablecoins from non-segregated strategies.

Option 3 is probably the next best choice in my view, and if we developed a strong implementation and a way to handle the usability complexity it might be worth exploring. I also feel that we should never reach a point where we have to rely on this for protection. If we have we've made some serious mistakes.
