### ISSUE TITLE
modifiable APY dropdown selection

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#950]
The Dapp should offer an option to display either 1y, 30d & 7d APYs via a dropdown from the balance header. 30 day and 1 year APYs are already available from the  `ContractStore` module. They 7day apy needs to be fetched and stored to `ContractStore` via: https://analytics.ousd.com/api/v1/apr/trailing/7
UI should look like this: 

![Apy_change](https://user-images.githubusercontent.com/579910/158983470-0354417a-c330-4ad4-aab6-74cb6bcfc734.png)

**Comment by micahalcorn** [comment]
It may be more involved, but I think we initially intended to have 7-day as well and apparently the old mockup had 3-day too. I'm happy to start with just 30 and 365 although it might make more sense to say "1y" instead of "365d".

Separately, it would be good to add the same feature to https://analytics.ousd.com/ and https://analytics.ousd.com/apy but that can also be a separate project.

**Comment by sparrowDom** [comment]
Good points thanks, have updated my initial comment with your feedback. Also deploying this massive commit that makes it possible to query 7 day APY (previously under 10 day APYs weren't queryable): https://github.com/OriginProtocol/ousd-analytics/commit/6f6f7effabc9b404a390761f0ce0b3c0f238e81a

**Comment by joshfraser** [comment]
Most of the stable coin farmers I've talked to want to be stay in their positions for at least a few months. As a result, 30d,60d,90d are likely the most useful. I'd include 7d and 365d too.

IMO it would look better if we swapped the order to have the drop-down come before the label.

**Comment by rolandpo** [comment]
done in #952
