### ISSUE TITLE
Progressive loading of the history page?

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin-dollar#978]
I have 26 pages of history in my History tab making it quite slow to load.

Is it possible to do progressive loading? It would be nice to load the first page of results before starting to process the following pages. If necessary, we could disable the filters until everything has loaded.

**Comment by sparrowDom** [comment]
This is partly solved via the: https://github.com/OriginProtocol/origin-dollar/pull/980

**Comment by sparrowDom** [comment]
We haven't done any pagination on the analytics or dapp side of this issue. The loading is very slow due to the huge amount of data that needs to go over the network. @rolandpo would you like to take on additional task and: 
- make analytics backend support pagination
- fetch data from the dapp using pagination

**Comment by rolandpo** [comment]
Sure 👍

**Comment by sparrowDom** [comment]
Just a heads up, while time passes and we have more rebase events each day, the performance impact of not using pagination is going to become more apparent. Especially on mobile devices where with slower CPUs.

**Comment by rolandpo** [comment]
done in #998
